version: '3.8'

services:
  luxe-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_URL=http://localhost
    ports:
      - "5443:443"
      - "5000:80"
      - "5001:5001"
      
    volumes:
      - luxe_http_data:/var/www/html
    networks:
      - luxe-network
      
  luxe-qr:
    build:
      context: .
      dockerfile: /whatsapp/Dockerfile
    environment:
      - APP_URL=http://localhost
    ports:
      - "3000:3000"
    volumes:
      - luxe_wa_data:/var/www/html
    networks:
      - luxe-network

  luxe-mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: em_db
      MYSQL_USER: em-user
      MYSQL_PASSWORD: secret
    volumes:
      - luxe_db_data:/var/lib/mysql
    networks:
      - luxe-network

networks:
  luxe-network:
    driver: bridge

volumes:
  luxe_db_data:
  luxe_http_data:
