name: Deploy to LUXE APP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install sshpass and Deploy
      - name: Deploy to Remote Server
        env:
          REMOTE_PASSWORD: 'AR!buJ25]a61bL'
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "$REMOTE_PASSWORD" ssh -o StrictHostKeyChecking=no root@103.56.148.122 << EOF
            cd /home/luxe/public_html/luxe-app
            git pull origin main
            service vite_dev stop
            service vite_dev start      
          EOF
